### ISSUE TITLE
typo / boot overlay not applied

### ISSUE THREAD

**Issue by emphasize** [NeonGeckoCom/neon-image-recipe#42]
[here](https://github.com/NeonGeckoCom/neon-image-recipe/blob/dacc6b3d71b970897c931ea5507f43857652798e/automation/prepare.sh#L53)
```diff
- if [[ "${image_file}" == *"ubuntu_22_04"* ]]; then
+ if [[ "${image_file}" == *ubuntu-22.04* ]]; then
```
Add., the output strings are in reverse

**Comment by NeonDaniel** [comment]
Good catch; missed this in that bigger refactor to support other base images
